# Generated by Django 4.2.1 on 2024-01-28 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('women', '0003_alter_women_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='women',
            name='is_published',
            field=models.BooleanField(choices=[(0, 'Not Published'), (1, 'Published')], default=1),
        ),
    ]
